version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: etudiants_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    networks:
      - app-network
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
  api:
    build: ./api-etudiant-departement
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/etudiants_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge