spring.application.name=api-etudiant-departement
spring.datasource.url=jdbc:postgresql://db:5432/etudiants_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
spring.data.redis.host=localhost
spring.data.redis.port=6379

